name: Version approve and set auto merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Approve Dependabot PRs
        if: contains( github.event.pull_request.labels.*.name, 'automated-pr')
        run: gh pr review --approve "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Enable auto-merge for Dependabot PRs
        if: contains( github.event.pull_request.labels.*.name, 'automated-pr')
        run: gh pr merge --auto --rebase "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ github.token }}
